- name: Agency for the Cooperation of Energy Regulators [ACER]
  landing: https://www.acer.europa.eu/the-agency/careers/vacancies
  type: js
- name: Body of European Regulators for Electronic Communications [BEREC]
  landing: https://www.berec.europa.eu/en/vacancies
  type: js
- name: Committee of Regions  [CR]
  landing: https://cor.europa.eu/en/about/work-us/jobs
  type: js
- name: Community Plant Variety Office [CPVO]
  landing: https://cpvo.europa.eu/en/about-us/recruitment#page-search---index
  type: js
- name: Council of the European Union  [CEU]
  landing: https://www.eeas.europa.eu/eeas/vacancies_en?f%5B0%5D=vacancy_site%3AEEAS&f%5B1%5D=vacancy_site%3AEEAS
  type: js
- name: European Agency for Safety and Health at Work [EU-OSHA]
  landing: https://osha.europa.eu/en/careers
  type: js
- name: European Agency for the Management of Operational Cooperation at the External
    Borders [FRONTEX]
  landing: https://www.frontex.europa.eu/careers/vacancies/open-vacancies/
  type: js
- name: European Agency for the operational management of large-scale IT systems in
    the area of freedom, security and justice  [EU-LISA]
  landing: https://erecruitment.eulisa.europa.eu/en
  type: js
- name: European Asylum Support Office [EASO]
  landing: https://euaa.europa.eu/careers/vacancies
  type: js
- name: European Atomic Energy Community [Euratom]
  landing: https://eu-careers.europa.eu/en/job-opportunities/open-for-application
  type: js
- name: European Aviation Safety Agency [EASA]
  landing: https://careers.easa.europa.eu/go/All-Jobs/8855901/
  type: js
- name: European Banking Authority [EBA]
  landing: https://www.careers.eba.europa.eu/en
  type: js
- name: European Central Bank [ECB]
  landing: https://talent.ecb.europa.eu/careers
  type: js
- name: European Centre for Disease Prevention and Control [ECDC]
  landing: https://erecruitment.ecdc.europa.eu/?page=advertisement
  type: error
- name: European Centre for the Development of Vocational Training [CEDEFOP]
  landing: https://www.cedefop.europa.eu/en/about-cedefop/job-opportunities/vacancies?search=&year=&sort_order=DESC&items_per_page=60
  type: js
- name: European Chemicals Agency [ECHA]
  landing: https://jobs.echa.europa.eu/psp/pshrrcr/EMPLOYEE/HRMS/c/HRS_HRAM.HRS_APP_SCHJOB.GBL?FOCUS=Applicant&languageCd=ENG
  type: js
- name: European Commission [EC]
  landing: https://eu-careers.europa.eu/en/job-opportunities/open-vacancies/ec_vacancies?field_epso_domain_target_id=&field_epso_type_of_contract_target_id=770&field_epso_location_target_id=All
  type: js
- name: European Council  [Council]
  landing: https://www.consilium.europa.eu/en/general-secretariat/jobs/vacancies/
  type: js
- name: European Court of Auditors [ECA]
  landing: https://www.eca.europa.eu/en/job-opportunities#page-search---index---lang---en_US
  type: js
- name: European Data Protection Supervisor [EDPS]
  landing: https://www.edps.europa.eu/about/office-edps/careers/our-vacancies_en
  type: js
- name: European Defence Agency [EDA]
  landing: https://eda.europa.eu/careers/current-vacancies
  type: js
- name: European Environment Agency [EEA]
  landing: https://jobs.eea.europa.eu/
  type: js
- name: European External Action Service [EEAS]
  landing: https://www.eeas.europa.eu/eeas/vacancies_en?f%5B0%5D=vacancy_site%3AEEAS
  type: js
- name: European Fisheries Control Agency [EFCA]
  landing: https://www.efca.europa.eu/en/content/recruitment
  type: js
- name: European Food Safety Authority [EFSA]
  landing: https://careers.efsa.europa.eu/jobs/search/1148737
  type: js
- name: European Foundation for the Improvement of Living and Working Conditions [EUROFOUND]
  landing: https://www.eurofound.europa.eu/en/vacancies
  type: js
- name: European GNSS Agency [GSA]
  landing: https://www.euspa.europa.eu/opportunities/careers
  type: js
- name: European Institute for Gender Equality [EIGE]
  landing: https://eige.europa.eu/about/recruitment
  type: js
- name: European Institute of Innovation and Technology [EIT]
  landing: https://www.eit.europa.eu/work-with-us/careers/vacancies/open
  type: js
- name: European Insurance and Occupational Pensions Authority [EIOPA]
  landing: https://eiopa.gestmax.eu/search
  type: js
- name: European Investment Bank [EIB]
  landing: https://erecruitment.eib.org/psc/hr/EIBJOBS/CAREERS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_SCHJOB_FL&Action=U&Focus=Applicant&SiteId=1
  type: js
- name: European Maritime Safety Agency [EMSA]
  landing: https://www.emsa.europa.eu/jobs/vacancies.html
  type: js
- name: European Medicines Agency [EMA]
  landing: https://careers.ema.europa.eu/search/
  type: js
- name: European Monitoring Centre for Drugs and Drug Addiction [EMCDDA]
  landing: https://e-recruitment.emcdda.europa.eu/e-recruitment/jobvacancies
  type: js
- name: European Network and Information Security Agency [ENISA]
  landing: https://www.enisa.europa.eu/careers
  type: js
- name: European Ombudsman [Ombudsman]
  landing: https://www.ombudsman.europa.eu/en/office/careers
  type: js
- name: European Parliament  [EP]
  landing: https://apply4ep.gestmax.eu/search/index/lang/en_US
  type: js
- name: European Personnel Selection Office [EPSO]
  landing: https://eu-careers.europa.eu/en/non-permanent-contract-ec
  type: js
- name: European Police College [CEPOL]
  landing: https://www.cepol.europa.eu/work-us/careers/vacancies
  type: js
- name: European Police Office [EUROPOL]
  landing: https://www.europol.europa.eu/careers-procurement/open-vacancies
  type: js
- name: European Railway Agency [ERA]
  landing: https://www.era.europa.eu/agency-you/recruitment/vacancies
  type: js
- name: European Securities and Markets Authority [ESMA]
  landing: https://esmacareers.adequasys.com/
  type: js
- name: European Stability Mechanism [ESM]
  landing: https://vacancies.esm.europa.eu/#en/sites/CX
  type: js
- name: European Training Foundation [ETF]
  landing: https://www.etf.europa.eu/en/about/recruitment
  type: js
- name: European Union Agency for Fundamental Rights [FRA]
  landing: https://fra.europa.eu/en/about-fra/recruitment/vacancies
  type: js
- name: European Union Institute for Security Studies [EUISS]
  landing: https://www.iss.europa.eu/opportunities
  type: js
- name: European Union Intellectual Property Office [EUIPO]
  landing: https://career012.successfactors.eu/career?company=C0001250580P
  type: js
- name: European Union Satellite Centre [SATCEN]
  landing: https://www.satcen.europa.eu/recruitment/jobs
  type: js
- name: Nordic Development Fund [NDF]
  landing: https://www.ndf.int/contact-us/jobs.html
  type: js
- name: Publications Office of the European Union [POEU]
  landing: .nan
  type: error
- name: Single Resolution Board [SRB]
  landing: .nan
  type: error
- name: The European Union's Judicial Cooperation Unit [EUROJUST]
  landing: .nan
  type: error
- name: Translation Centre for the Bodies of the European Union [CdT]
  landing: .nan
  type: error
- name: European Public Prosecutor's Office (in preparation) [EPPO]
  landing: .nan
  type: error
- name: European Union [EU]
  landing: .nan
  type: error
- name: European Financial Stability Facility [EFSF]
  landing: .nan
  type: error
- name: European Telecommunications Satellite Organization [EUTELSAT]
  landing: .nan
  type: error
- name: ATHENA Mechanism
  landing: .nan
  type: error
- name: Africa Finance Corporation [AFC]
  landing: .nan
  type: error
- name: African Development Bank [AfDB]
  landing: .nan
  type: error
- name: African Development Bank Group [AfDB]
  landing: .nan
  type: error
- name: African Development Fund [AfDF]
  landing: .nan
  type: error
- name: African Export-Import Bank [Afreximbank]
  landing: .nan
  type: error
- name: African Union  [AU]
  landing: .nan
  type: error
- name: Andean Development Corporation [ADC]
  landing: .nan
  type: error
- name: Arab Bank for Economic Development in Africa [BADEA]
  landing: .nan
  type: error
- name: Arab Fund for Economic and Social Development [AFESD]
  landing: .nan
  type: error
- name: Arab Monetary Fund [AMF]
  landing: .nan
  type: error
- name: Asian Clearing Union [ACU]
  landing: .nan
  type: error
- name: Asian Development Bank [ADB]
  landing: .nan
  type: error
- name: Asian Development Fund  [AsDF]
  landing: .nan
  type: error
- name: Association of Southeast Asian Nations  [ASEAN]
  landing: .nan
  type: error
- name: Bank for International Settlements [BIS]
  landing: .nan
  type: error
- name: Banque des Etats de l'Afrique Centrale [BEAC]
  landing: .nan
  type: error
- name: Caribbean Community and Common Market  [CARICOM]
  landing: .nan
  type: error
- name: Caribbean Development Bank [CDB]
  landing: .nan
  type: error
- name: Central African States Development Bank [CASDB]
  landing: .nan
  type: error
- name: Central American Bank for Economic Integration [CABEI]
  landing: .nan
  type: error
- name: Central American Common Market  [CACM]
  landing: .nan
  type: error
- name: Colombo Plan
  landing: .nan
  type: error
- name: East African Development Bank [EADB]
  landing: .nan
  type: error
- name: Eastern Caribbean Central Bank [ECCB]
  landing: .nan
  type: error
- name: Economic Community of West African States  [ECOWAS]
  landing: .nan
  type: error
- name: ECOWAS Bank for Investment and Development [EBID]
  landing: .nan
  type: error
- name: Eurasian Development Bank [EDB]
  landing: .nan
  type: error
- name: European Broadcasting Union [EBU]
  landing: .nan
  type: error
- name: European Company for the Financing of Railroad Rolling Stock  [EUROFIMA]
  landing: .nan
  type: error
- name: European Free Trade Association  [EFTA]
  landing: .nan
  type: error
- name: European Organization for Nuclear Research  [CERN]
  landing: .nan
  type: error
- name: Foreign Trade Bank of Latin America [Bladex]
  landing: .nan
  type: error
- name: Inter-American Development Bank [IADB]
  landing: .nan
  type: error
- name: Inter-American Investment Corporation [IIC]
  landing: .nan
  type: error
- name: International Bank for Economic Cooperation [IBEC]
  landing: .nan
  type: error
- name: International Bank for Reconstruction and Development (IBRD) [IBRD]
  landing: .nan
  type: error
- name: International Centre for Settlement of Investment Disputes - WB Group [ICSID]
  landing: .nan
  type: error
- name: International Civil Aviation Organization  [ICAO]
  landing: .nan
  type: error
- name: International Committee of the Red Cross  [ICRC]
  landing: .nan
  type: error
- name: International Cotton Advisory Committee  [ICAC]
  landing: .nan
  type: error
- name: International Development Association - WG Group [IDA]
  landing: .nan
  type: error
- name: International Finance Corporation [IFC]
  landing: .nan
  type: error
- name: International Investment Bank [IIB]
  landing: .nan
  type: error
- name: International Jute Study Group  [IJSG]
  landing: .nan
  type: error
- name: International Labour Organization  [ILO]
  landing: .nan
  type: error
- name: International Monetary Fund [IMF]
  landing: .nan
  type: error
- name: International Organisation for Migration [IOM]
  landing: .nan
  type: error
- name: International Telecommunication Union  [ITU]
  landing: .nan
  type: error
- name: Islamic Development Bank  [IDB]
  landing: .nan
  type: error
- name: Latin American and the Caribbean Economic System  [SELA]
  landing: .nan
  type: error
- name: Latin American Association of Development Financing Institutions  [ALIDE]
  landing: .nan
  type: error
- name: Latin American Energy Organization  [OLADE]
  landing: .nan
  type: error
- name: Latin American Integration Association  [LAIA]
  landing: .nan
  type: error
- name: Latin American Reserve Fund [LARF]
  landing: .nan
  type: error
- name: League of Arab States  [LAS]
  landing: .nan
  type: error
- name: Multilateral Investment Guarantee Agency - WB Group [MIGA]
  landing: .nan
  type: error
- name: North American Development Bank  [NADB]
  landing: .nan
  type: error
- name: Organisation of Eastern Caribbean States  [OECS]
  landing: .nan
  type: error
- name: Organization of American States  [OAS]
  landing: .nan
  type: error
- name: Organization of Arab Petroleum Exporting Countries  [OAPEC]
  landing: .nan
  type: error
- name: Organization of Central American States  [OCAS]
  landing: .nan
  type: error
- name: South Asian Association for Regional Cooperation  [SAARC]
  landing: .nan
  type: error
- name: Special Development Fund (related to the Caribbean Development Bank) [SDF]
  landing: .nan
  type: error
- name: United Nations Children's Fund  [UNICEF]
  landing: .nan
  type: error
- name: United Nations Conference on Trade and Development  [UNCTAD]
  landing: .nan
  type: error
- name: United Nations, its committees, funds and programmes, other [-]
  landing: .nan
  type: error
- name: Universal Postal Union  [UPU]
  landing: .nan
  type: error
- name: West African Central Bank [BCEAO]
  landing: .nan
  type: error
- name: West African Economic and Monetary Union [WAEMU]
  landing: .nan
  type: error
- name: West African Economic Community  [WAEC]
  landing: .nan
  type: error
- name: West African Health Organisation [WAHO]
  landing: .nan
  type: error
- name: West African Monetary Agency  [WAMA]
  landing: .nan
  type: error
- name: West African Monetary Institute [WAMI]
  landing: .nan
  type: error
- name: World Council of Churches  [WCC]
  landing: .nan
  type: error
- name: World Health Organization  [WHO]
  landing: .nan
  type: error
- name: World Intellectual Property Organization  [WIPO]
  landing: .nan
  type: error
- name: World Meteorological Organization  [WMO]
  landing: .nan
  type: error
- name: World Trade Organization  [WTO]
  landing: .nan
  type: error
- name: Black Sea Trade and Development Bank [BSTDB]
  landing: .nan
  type: error
- name: Computer Emergency Response Team [CERT]
  landing: .nan
  type: error
- name: Council of Europe  [CE]
  landing: .nan
  type: error
- name: Council of Europe Development Bank [CEB]
  landing: .nan
  type: error
- name: EU-Africa Infrastructure Trust Fund  [EU-ATIF]
  landing: .nan
  type: error
- name: European Bank for Reconstruction and Development [EBRD]
  landing: .nan
  type: error
- name: European Centre for Medium-Range Weather Forecasts [ECMWF]
  landing: .nan
  type: error
- name: European Molecular Biology Laboratory [EMBL]
  landing: .nan
  type: error
- name: European Organisation for the Exploitation of Meteorological Satellites [EUMETSAT]
  landing: .nan
  type: error
- name: European Organisation for the Safety of Air Navigation [EUROCONTROL]
  landing: .nan
  type: error
- name: European Patent Office [EPO]
  landing: .nan
  type: error
- name: European Southern Observatory [ESO]
  landing: .nan
  type: error
- name: European Space Agency  [ESA]
  landing: .nan
  type: error
- name: Facility for Euro-Mediterranean Investment and Partnership [FEMIP]
  landing: .nan
  type: error
- name: "Fonds Belgo-Congolais D\u2019Amortissement et de Gestion [RDC]"
  landing: .nan
  type: error
- name: Food and Agricultural Organization  [FAO]
  landing: .nan
  type: error
- name: Fusion for Energy [F4E]
  landing: .nan
  type: error
- name: Intergovernmental Council of Copper Exporting Countries  [CIPEC]
  landing: .nan
  type: error
- name: International Atomic Energy Agency  [IAEA]
  landing: .nan
  type: error
- name: International Cocoa Organization  [ICCO]
  landing: .nan
  type: error
- name: International Coffee Organization  [ICO]
  landing: .nan
  type: error
- name: International Copper Study Group [ICSG]
  landing: .nan
  type: error
- name: International Finance Facility for Immunisation [IFFIm]
  landing: .nan
  type: error
- name: International Fund for Agricultural Development [IFAD]
  landing: .nan
  type: error
- name: International Grains Council  [IGC]
  landing: .nan
  type: error
- name: International Lead and Zinc Study Group  [ILZSG]
  landing: .nan
  type: error
- name: International Maritime Organization  [IMO]
  landing: .nan
  type: error
- name: International Maritime Satellite Organization  [INMARSAT]
  landing: .nan
  type: error
- name: International Olive Oil Council  [IOOC]
  landing: .nan
  type: error
- name: International Rubber Study Group  [IRSG]
  landing: .nan
  type: error
- name: International Sugar Organization  [ISO]
  landing: .nan
  type: error
- name: International Union of Credit and Investment Insurers [Berne Union]
  landing: .nan
  type: error
- name: Neighbourhood Investment Facility  [NIF]
  landing: .nan
  type: error
- name: Nordic Investment Bank [NIB]
  landing: .nan
  type: error
- name: North Atlantic Treaty Organisation  [NATO]
  landing: .nan
  type: error
- name: OPEC Fund for International Development [OFID]
  landing: .nan
  type: error
- name: Organisation for Economic Co-operation and Development  [OECD]
  landing: .nan
  type: error
- name: Organization of the Petroleum Exporting Countries  [OPEC]
  landing: .nan
  type: error
- name: Paris Club Creditor Institutions  [Paris Club]
  landing: .nan
  type: error
- name: United Nations Educational, Scientific and Cultural Organization  [UNESCO]
  landing: .nan
  type: error
- name: World Tourism Organization [UNWTO]
  landing: .nan
  type: error
- name: The Permanent Court of Arbitration [PCA]
  landing: .nan
  type: error
- name: European Free Trade Association Court [EFTA COURT]
  landing: .nan
  type: error
- name: NATO Support and Procurement Organisation [NSPO]
  landing: .nan
  type: error
- name: The Eastern and Southern African Trade and Development Bank [TDB]
  landing: .nan
  type: error
- name: International Council for the Exploration of the Sea [ICES]
  landing: .nan
  type: error
- name: United Nations Relief and Works Agency for Palestine [UNRWA]
  landing: .nan
  type: error
- name: Asian Infrastructure Investment Bank [AIIB]
  landing: .nan
  type: error
- name: United Nations High Commissioner for Refugees [UNHCR]
  landing: .nan
  type: error
- name: United Nations Economic Commission for Europe [UNECE]
  landing: .nan
  type: error
- name: International Telecommunications Satellite Organisation [ITSO]
  landing: .nan
  type: error
- name: The Global Fund to Fight AIDS, Tuberculosis and Malaria [GLOBAL FUND]
  landing: .nan
  type: error
- name: United Nations Framework Convention for Climate Change [UNFCCC]
  landing: .nan
  type: error
- name: International Energy Agency [IEA]
  landing: .nan
  type: error
