# sites/config.yaml
- name: ecmwf
  landing: https://ecmwf.int/en/about/jobs
  type: ajax
  ajax_path_xpath: '//input[@id="requestUrl"]/@data-request-url'
  list_xpath: '//div[contains(@class,"job-card")]'
  detail_link:    './/a[starts-with(@data-testid,"a-job-detail")]/@href'

- name: other-static
  landing: https://other-company.com/careers
  type: static
  list_xpath: '//ul[@class="jobs"]/li'
  detail_link: './a/@href'

- name: graphql-site
  landing: https://graphql-jobs.com
  type: graphql
  graphql_endpoint: https://graphql-jobs.com/api
  graphql_query: |
    { jobs(limit:100, offset:0) { id title url } }
  json_path: $.data.jobs[*]

- name: js-heavy
  landing: https://js-jobs.com
  type: splash
  splash_endpoint: splash:8050/render.html
  splash_args: {wait:2}
  list_xpath: '//div[@class="job"]'
  detail_link: './/a/@href'
